[package]
name = "evm"
version = "0.1.0"
authors = ["Cryptape Technologies <contact@cryptape.com>"]
edition = "2018"

[dependencies]
ethereum-types = "0.4"
hex = "0.3"
keccak-hash = "0.1"

[features]
test = []
